### ISSUE TITLE
Example of `_rank.csv` file

### ISSUE THREAD

**Issue by zhenhuan-yang** [rutgerswiselab/user-fairness#2]
Hi, thanks for your contributions. When I read your code, I have a question -- for each `uid`, do i include the `score` and `label` on EVERY or top-N `iid` in my `_rank.csv` file? If it is top-N how should I choose N? Could you please provide an example `_rank.csv` file such as `NCF_rank.csv` in `model.py`?

**Comment by yunqi-li** [comment]
Hi,
Thank you for your question. The `_rank.csv` file contains four columns: uid, iid, label, score. For each uid, you can either choose top-N or every iid in the _rank.csv file. It depends on your use case and our model do not have requirements on that.
