### ISSUE TITLE
[ASK] Why you did not provide at least one complete example of you codes?!

### ISSUE THREAD

**Issue by rahmanidashti** [rutgerswiselab/user-fairness#4]
Hi all,

I think that would be better when you release your code you also provide a complete example of what you did and at least one reproducible result on one dataset. This way researcher can be sure about the reproducibility of your codes and results. So, I think you can put the ranking file on NCF as it is your current example in the code.

Thanks

**Comment by yunqi-li** [comment]
Hi @rahmanidashti, thanks for pointing out the missing files. We have uploaded the compressed *_rank.csv files to each dataset folder. We provide NCF and biasedMF model-generated ranking files for your reference.
