### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by JingsenZhang** [rutgerswiselab/user-fairness#6]
Hi,
Why are the results consistent before and after optimization?
Does that mean the re-ranking didn't work? Or is my code set up wrong?
![image](https://user-images.githubusercontent.com/36886184/145929205-cfce4b1c-eb6e-4409-8f9f-8a180bbdc0d3.png)

**Comment by JingsenZhang** [comment]
At the same time, when I change the value of _epsilon_, I get the same result. What causes this?

**Comment by JingsenZhang** [comment]
resolved

**Comment by TaoHaoTian** [comment]
I have the same problem. How can I solve it？
